# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(222, 262)
        Dialog.setMinimumSize(QtCore.QSize(222, 262))
        Dialog.setMaximumSize(QtCore.QSize(222, 262))
        Dialog.setWindowTitle("")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 209))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.hours_input = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.hours_input.setMaximum(23)
        self.hours_input.setObjectName("hours_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hours_input)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.minutes_input = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.minutes_input.setMaximum(59)
        self.minutes_input.setObjectName("minutes_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minutes_input)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.monday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.monday.setObjectName("monday")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.monday)
        self.tuesday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.tuesday.setObjectName("tuesday")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tuesday)
        self.wendesday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.wendesday.setObjectName("wendesday")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.wendesday)
        self.thursday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.thursday.setObjectName("thursday")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.thursday)
        self.friday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.friday.setObjectName("friday")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.friday)
        self.saturday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.saturday.setObjectName("saturday")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.saturday)
        self.sunday = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.sunday.setObjectName("sunday")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sunday)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 220, 201, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_btn.setEnabled(False)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "Час:"))
        self.label_2.setText(_translate("Dialog", "Минута:"))
        self.label_3.setText(_translate("Dialog", "Дни:"))
        self.monday.setText(_translate("Dialog", "Понедельник"))
        self.tuesday.setText(_translate("Dialog", "Вторник"))
        self.wendesday.setText(_translate("Dialog", "Среда"))
        self.thursday.setText(_translate("Dialog", "Четверг"))
        self.friday.setText(_translate("Dialog", "Пятница"))
        self.saturday.setText(_translate("Dialog", "Суббота"))
        self.sunday.setText(_translate("Dialog", "Воскресенье"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.cancel_btn.setText(_translate("Dialog", "Отмена"))
