# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 160)
        Dialog.setMinimumSize(QtCore.QSize(399, 160))
        Dialog.setMaximumSize(QtCore.QSize(399, 160))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 120, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_btn.setEnabled(False)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 100))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.hours = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.hours.setMaximum(23)
        self.hours.setObjectName("hours")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hours)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.minutes = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.minutes.setMaximum(59)
        self.minutes.setObjectName("minutes")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minutes)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.seconds = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.seconds.setMaximum(59)
        self.seconds.setObjectName("seconds")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.seconds)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.message_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.message_input.setObjectName("message_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.message_input)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Установить время"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.cancel_btn.setText(_translate("Dialog", "Отмена"))
        self.label.setText(_translate("Dialog", "Часы:"))
        self.label_2.setText(_translate("Dialog", "Минуты:"))
        self.label_3.setText(_translate("Dialog", "Секунды:"))
        self.label_4.setText(_translate("Dialog", "Сообщение:"))
        self.message_input.setText(_translate("Dialog", "Время истекло"))
